Implemented swiper.
byte-pushers/chucks-pick3 pull request #597
Opened 2022-01-24 19:22 UTC by ocampd1

2022-01-31 20:00 UTC, pouncilt requested changes
Also ensure the code coverage is up to par.

2022-01-31 20:00 UTC, pouncilt commented on chucks-pick3-mobile/src/app/pages/home/home.page.html
> +  <swiper #pick3DrawDateCards [config]="slideOpts" [slidesPerView]="1" style="height: 100%" (slideChange)="initializePick3DrawDateCard($event)"
Should we use Style class instead of in-line style here?

2022-02-02 23:59 UTC, ocampd1 commented on chucks-pick3-mobile/src/app/pages/home/home.page.ts
> +        } else {
Removed

2022-02-02 23:59 UTC, ocampd1 commented on chucks-pick3-mobile/src/app/pages/home/home.page.ts
> +        // const nextPick3DrawDate = this.pick3DrawDateDecks[activeIndex];
Removed

2022-02-02 23:59 UTC, ocampd1 commented on chucks-pick3-mobile/src/app/pages/home/home.page.ts
> +        // TODO Determine if we are swiping left(activeIndex -1) or right (activeIndex +1) on slides
No longer needed, removed

2022-02-02 23:59 UTC, ocampd1 commented on chucks-pick3-mobile/src/app/pages/home/home.page.ts
> +  ngAfterViewInit() {
Removed method

2022-02-02 23:59 UTC, ocampd1 commented on chucks-pick3-mobile/src/app/pages/home/home.page.ts
> +  slideOpts = {
Removed from code

2022-02-07 20:14 UTC, merged